export const authors = [
  "RT en Español\n , RT en Español",
  "ERIC KIM",
  "חדשות",
  "aol.com",
  "Freddie Clayton",
  "Monika Ghosh",
  "Reuters",
  "marca.com",
  "Bleichmar Fonti & Auld",
  "Stace Fernandez",
  "Sarang Sheth",
  "Mónica Millán Valera",
  "Thom Hartmann",
  "Eoin Burke-Kennedy",
  "Tim Niendorf",
  "Hanne Hattrem",
  "Helmut Becker",
  "SG.hu",
  "info@bright.nl (Erwin van der Zande)",
  "Lawton",
  "Ritu Singh",
  "Tim Baker",
  "Habertürk",
  "Ştefan Stan",
  "Ana Sofia Neto",
  "Peter Aitken",
  "DEMOS, Desarrollo de Medios, S.A. de C.V.",
  "Bob Jouy",
  "BiktorSergeev (МТС)",
  "Investing.com",
  "Pierluigi Paganini",
  "TT",
  "Katie Teague",
  "Tobias Österberg/TT",
  "Матвей Крылов",
  "Théotim Raguet",
  "Beatrice Parrino",
  "Raven Louisa Rascher,Daniel Weidmann,Jan Jessen,Christian Unger,Dominik Bath,Martin Nefzger",
  "Алексей Сычёв",
  "Martín De Ambrosio",
  "Matías Galán,Ricardo de la Peña",
  "Adam B. Vary",
  "Forbes",
  "ET Online",
  "T.B",
  "Bloomberg",
  "Adam Kurfürst",
  "Der Tagesspiegel",
  "ZEIT ONLINE: News -",
  "STERN.de",
  "TİMUR SIRT",
  "Luciana Vázquez",
  "redazione@ilgiornale-web.it (Valeria Robecco)",
  "AP",
  "Sebastián Campanario",
  "Geraldine Herbert",
  "Thairath",
  "Anthony Garreffa",
  "Mike Wendling",
  "Abhimanyu Ghoshal",
  "finance.yahoo.com",
  "Esther Vargas",
  "notateslaapp.com",
  "岡本玄介",
  "bringatrailer",
  "The Feed",
  "newsweek.com",
  "engadget.com",
  "Benjamin Wallace-Wells",
  "wnd.com",
  "PC Mag",
  "Bloomberg News",
  "Ross Pomeroy, Real Clear Wire",
];
