export const categories = [
  "football",
  "world news",
  "australia news",
  "life and style",
  "travel",
  "politics",
  "us news",
  "music",
  "food",
  "business",
  "money",
  "stage",
  "society",
  "film",
  "uk news",
  "opinion",
  "global development",
  "education",
  "books",
  "art and design",
  "television & radio",
  "fashion",
  "environment",
  "work redefined",
  "sport",
  "culture",
];
